### ISSUE TITLE
Wiring NEO-6M module

### ISSUE THREAD

**Issue by pierrebak** [nopnop2002/esp-idf-GPS-View#4]
hello, I could flash the firmware but my NE06M comes with TX and RX ( not I2C with SCL and SLA), 
so I haven't any clue on how to wire it.

Thanks,

**Comment by nopnop2002** [comment]
You can use GROVE port as UART RXD.
SCL of GROVE(Yellow) is GPIO22.
SDA of GROVE(White) is GPIO21.
